### PR TITLE
Allow for passing a yaml inventory instead of a path

### PR DESCRIPTION
**Pull request by flaper87**

### CODE REVIEW

**Comment by flaper87** [comment]
Mistral seems to be interpreting the `inventory` property as an attribute and fails to register the action. Need to find a better way to do this

**Comment by flaper87** [comment]
```
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mistral/db/v2/sqlalchemy/api.py", line 622, in create_action_definition
    a_def.save(session=session)
  File "/usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/models.py", line 50, in save
    session.flush()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1337, in _handle_dbapi_exception
    util.raise_from_cause(newraise, exc_info)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 608, in _init_compiled
    for key in compiled_params
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 608, in <genexpr>
    for key in compiled_params
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 982, in process
    return process_param(value, dialect)
  File "/usr/lib/python2.7/site-packages/mistral/db/sqlalchemy/types.py", line 32, in process_bind_param
    value = jsonutils.dumps(value)
  File "/usr/lib/python2.7/site-packages/oslo_serialization/jsonutils.py", line 190, in dumps
    return json.dumps(obj, default=default, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
oslo_db.exception.DBError: (exceptions.ValueError) Circular reference detected [SQL: u'INSERT INTO action_definitions_v2 (scope, project_id, created_at, updated_at, id, name, definition, spec, tags, is_system, description, input, action_class, attributes) VALUES (%(scope)s, %(project_id)s, %(created_at)s, %(updated_at)s, %(id)s, %(name)s, %(definition)s, %(spec)s, %(tags)s, %(is_system)s, %(description)s, %(input)s, %(action_class)s, %(attributes)s)'] [parameters: [{'definition': None, 'name': 'ansible-playbook', 'tags': None, 'action_class': 'mistral_ansible_actions.AnsiblePlaybookAction', 'is_system': True, 'updated_at': None, 'input': 'playbook, limit_hosts=null, remote_user=null, become=null, become_user=null, extra_vars=null, inventory=null', 'scope': 'public', 'attributes': {'inventory': <property object at 0x66e7f18>}, 'spec': None, 'description': None}]]
```

**Comment by d0ugal** [comment]
@flaper87 https://review.openstack.org/#/c/460206/ - that should fix the error you are seeing.

**Review by d0ugal — APPROVED** [review]

**Comment by flaper87** [comment]
@d0ugal thanks, merging then.

**Pull request merged**
